---

name: "CI X64"

# yamllint disable-line rule:truthy
on:
  push:
    paths-ignore:
      - '*.md'

  pull_request:
    paths-ignore:
      - '*.md'

  workflow_dispatch:
    paths-ignore:
      - '*.md'

jobs:
  main:
    name: "X86: ${{ matrix.shell }} on ${{ matrix.image }}"
    strategy:
      fail-fast: false
      matrix:
        shell: [bash, zsh]  # Currently no ash
        image: [alpine, debian, archlinux]

    container:
      image: ${{ matrix.image }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install
        run: |
          case "${{ matrix.image }}" in
            alpine)
              apk update
              apk add which bash ${{ matrix.shell }}
              ;;
            debian)
              apt-get update
              apt-get install -y ${{ matrix.shell }}
              ;;
            archlinux)
              pacman -Sy --noconfirm which ${{ matrix.shell }}
              ;;
          esac

      - name: Run
        uses: ./.github/actions/test
        with:
          shell: ${{ matrix.shell }}
